services:
  postgres_db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: level_editor_local
    volumes:
      - ../db:/var/lib/postgresql/data
  api:
    build:
        context: ../backend
        dockerfile: Dockerfile
    ports:
      - "5433:3000"
    environment:
        DATABASE_URL: postgres://postgres:postgres@postgres_db:5432/level_editor_local
        SECRET_KEY: SUPER_SECRET_KEY
