services:
  postgres_db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: level_editor
    volumes:
      - ../db:/var/lib/postgresql/data